[package]
name = "amon-cli"
description = "Run coding agents behind a lens"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "amon"
path = "src/main.rs"

[dev-dependencies]
libc = { workspace = true }
portable-pty = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[dependencies]
amon-daemon = { workspace = true }
amon-integration = { workspace = true }
amon-protocol = { workspace = true }
amon-wrapper = { workspace = true }
clap = { workspace = true }
libc = { workspace = true }
serde_json = { workspace = true }
