[package]
name = "gaze-cli"
description = "Run coding agents behind a lens"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "gaze"
path = "src/main.rs"

[dev-dependencies]
portable-pty = { workspace = true }
serde_json = { workspace = true }

[dependencies]
gaze-daemon = { workspace = true }
gaze-integration = { workspace = true }
gaze-protocol = { workspace = true }
gaze-wrapper = { workspace = true }
portable-pty = { workspace = true }
serde_json = { workspace = true }
