#!/usr/bin/env bash
# Re-derive every vendored file from herdr. See docs/adr/0005.
#
# Vendored files are never hand-edited: this script is the only thing that
# writes them. To move to a newer herdr, bump HERDR_COMMIT, run it, and review
# the diff.
set -euo pipefail

HERDR_REPO="https://github.com/ogulcancelik/herdr"
HERDR_COMMIT="514e4465ee33d4d81682d06ee2934483982a54ed"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cache="${AMON_VENDOR_CACHE:-${TMPDIR:-/tmp}/amon-vendor-herdr}"
patches="$repo_root/vendor/patches"

# upstream path -> destination, relative to the repo root. The multiplexer's
# own pane/runtime plumbing is deliberately absent: amon spawns its own PTY and
# only needs the state machine.
FILES=(
    "src/detect/mod.rs                  crates/amon-detect/src/vendor/detect/mod.rs"
    "src/detect/manifest.rs             crates/amon-detect/src/vendor/detect/manifest.rs"
    "src/detect/manifest_update.rs      crates/amon-detect/src/vendor/detect/manifest_update.rs"
    "src/detect/manifest/tests.rs       crates/amon-detect/src/vendor/detect/manifest/tests.rs"
    "src/terminal/id.rs                 crates/amon-term/src/vendor/terminal/id.rs"
    "src/terminal/title.rs              crates/amon-term/src/vendor/terminal/title.rs"
    "src/terminal/metadata.rs           crates/amon-term/src/vendor/terminal/metadata.rs"
    "src/terminal/state.rs              crates/amon-term/src/vendor/terminal/state.rs"
    "src/agent_resume.rs                crates/amon-term/src/vendor/agent_resume.rs"
    "src/metadata_tokens.rs             crates/amon-term/src/vendor/metadata_tokens.rs"
    "src/integration/mod.rs             crates/amon-integration/src/vendor/integration/mod.rs"
    "src/integration/actions.rs         crates/amon-integration/src/vendor/integration/actions.rs"
    "src/integration/command.rs         crates/amon-integration/src/vendor/integration/command.rs"
    "src/integration/config_edit.rs     crates/amon-integration/src/vendor/integration/config_edit.rs"
    "src/integration/env.rs             crates/amon-integration/src/vendor/integration/env.rs"
    "src/integration/file_ops.rs        crates/amon-integration/src/vendor/integration/file_ops.rs"
    "src/integration/registry.rs        crates/amon-integration/src/vendor/integration/registry.rs"
    "src/integration/targets.rs         crates/amon-integration/src/vendor/integration/targets.rs"
    "src/integration/types.rs           crates/amon-integration/src/vendor/integration/types.rs"
    "src/integration/version.rs         crates/amon-integration/src/vendor/integration/version.rs"
    "src/integration/tests.rs           crates/amon-integration/src/vendor/integration/tests.rs"
)

# Per-agent hook assets, copied with their directory layout. File names carry
# the herdr brand too, so they are renamed alongside their contents — the
# include_str! paths in targets.rs go through the same token map.
ASSET_DIRS=(
    "src/integration/assets              crates/amon-integration/src/vendor/integration/assets"
)

# Whole directories copied verbatim (detection manifests are pure data).
DIRS=(
    "src/detect/manifests                crates/amon-detect/src/vendor/detect/manifests"
)

fetch() {
    if [ ! -d "$cache/.git" ]; then
        echo "cloning herdr into $cache"
        git clone --quiet "$HERDR_REPO" "$cache"
    fi
    git -C "$cache" fetch --quiet origin "$HERDR_COMMIT" 2>/dev/null || git -C "$cache" fetch --quiet
    git -C "$cache" checkout --quiet "$HERDR_COMMIT"
}

# The herdr -> amon token map (ADR-0005). Order matters, and herdr.dev is
# deliberately preserved: amon pulls detection manifests from herdr's own
# catalog (ADR-0003).
rename_tokens() {
    sed -e 's|herdr\.dev|@@CATALOG_HOST@@|g' \
        -e 's|"herdr:|"amon:|g' \
        -e 's|HERDR_|AMON_|g' \
        -e 's|herdr-agent-state|amon-agent-state|g' \
        -e 's|herdr-manifest-|amon-manifest-|g' \
        -e 's|herdr-detect-|amon-detect-|g' \
        -e 's|herdr_|amon_|g' \
        -e 's|\bHerdr\b|Amon|g' \
        -e 's|pane\.report_agent_session|agent.report_session|g' \
        -e 's|pane\.report_agent|agent.report_state|g' \
        -e 's|PANE_ID|AGENT_ID|g' \
        -e 's|pane_id|agent_id|g' \
        -e 's|herdr|amon|g' \
        -e 's|HERDR|AMON|g' \
        -e 's|@@CATALOG_HOST@@|herdr.dev|g'
}

# Hook assets additionally rename herdr's CLI verb: hooks that cannot speak
# the socket protocol shell out to `herdr pane report-agent[-session]`, which
# in amon is `amon hook report-agent[-session]`. Matched as the invocation
# forms the assets actually contain (inline and argv-array), never as a bare
# word — `pane` also appears in prose comments, which must survive.
rename_asset_tokens() {
    rename_tokens | sed \
        -e 's|amon pane report-agent|amon hook report-agent|g' \
        -e 's|"pane",|"hook",|g'
}

header() {
    local upstream="$1" comment="$2"
    cat <<EOF
${comment} Generated by scripts/revendor.sh from herdr — do not edit by hand.
${comment} Upstream: ${HERDR_REPO}/blob/${HERDR_COMMIT}/${upstream}
${comment} Copyright Ogulcan Celik, licensed under the Apache License 2.0.
${comment} Modified only by the mechanical token map in scripts/revendor.sh.

EOF
}

vendor_file() {
    local upstream="$1" dest="$2" comment="$3" filter="${4:-rename_tokens}"
    mkdir -p "$(dirname "$repo_root/$dest")"
    {
        # A shebang only works on the first line, and hook assets are executed
        # directly by their agents — so the provenance header goes after it,
        # never before.
        if head -n1 "$cache/$upstream" | grep -q '^#!'; then
            head -n1 "$cache/$upstream"
            header "$upstream" "$comment"
            tail -n +2 "$cache/$upstream" | "$filter"
        else
            header "$upstream" "$comment"
            "$filter" <"$cache/$upstream"
        fi
    } >"$repo_root/$dest"
}

apply_patches() {
    [ -d "$patches" ] || return 0
    shopt -s nullglob
    for patch in "$patches"/*.patch; do
        echo "applying $(basename "$patch")"
        git -C "$repo_root" apply "$patch"
    done
    shopt -u nullglob
}

fetch

for entry in "${FILES[@]}"; do
    read -r upstream dest <<<"$entry"
    vendor_file "$upstream" "$dest" "//"
    echo "vendored $dest"
done

for entry in "${DIRS[@]}"; do
    read -r upstream dest <<<"$entry"
    rm -rf "${repo_root:?}/$dest"
    mkdir -p "$repo_root/$dest"
    for file in "$cache/$upstream"/*; do
        name="$(basename "$file")"
        vendor_file "$upstream/$name" "$dest/$name" "#"
    done
    echo "vendored $dest ($(find "$repo_root/$dest" -type f | wc -l) files)"
done

for entry in "${ASSET_DIRS[@]}"; do
    read -r upstream dest <<<"$entry"
    rm -rf "${repo_root:?}/$dest"
    while IFS= read -r file; do
        relative="${file#"$cache/$upstream/"}"
        renamed="${relative//herdr-/amon-}"
        case "$renamed" in
        *.js | *.ts) comment="//" ;;
        *) comment="#" ;;
        esac
        vendor_file "$upstream/$relative" "$dest/$renamed" "$comment" rename_asset_tokens
    done < <(find "$cache/$upstream" -type f)
    echo "vendored $dest ($(find "$repo_root/$dest" -type f | wc -l) files)"
done

apply_patches

# The token map does not preserve line width — `herdr` is five characters and
# `amon` four — so lines that upstream had already wrapped can now fit on one.
# rustfmt is part of the pipeline rather than a hand-edit (ADR-0005): it runs
# last, after the patches, whose context is therefore still upstream-shaped.
cargo fmt --manifest-path "$repo_root/Cargo.toml" --all
echo "formatted"

echo
echo "vendored from herdr @ ${HERDR_COMMIT}"
