#!/usr/bin/env bash
# Re-derive every vendored file from herdr. See docs/adr/0005.
#
# Vendored files are never hand-edited: this script is the only thing that
# writes them. To move to a newer herdr, bump HERDR_COMMIT, run it, and review
# the diff.
set -euo pipefail

HERDR_REPO="https://github.com/ogulcancelik/herdr"
HERDR_COMMIT="514e4465ee33d4d81682d06ee2934483982a54ed"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cache="${GAZE_VENDOR_CACHE:-${TMPDIR:-/tmp}/gaze-vendor-herdr}"
patches="$repo_root/vendor/patches"

# upstream path -> destination, relative to the repo root. The multiplexer's
# own pane/runtime plumbing is deliberately absent: gaze spawns its own PTY and
# only needs the state machine.
FILES=(
    "src/detect/mod.rs                  crates/gaze-detect/src/vendor/detect/mod.rs"
    "src/detect/manifest.rs             crates/gaze-detect/src/vendor/detect/manifest.rs"
    "src/detect/manifest_update.rs      crates/gaze-detect/src/vendor/detect/manifest_update.rs"
    "src/detect/manifest/tests.rs       crates/gaze-detect/src/vendor/detect/manifest/tests.rs"
    "src/terminal/id.rs                 crates/gaze-term/src/vendor/terminal/id.rs"
    "src/terminal/title.rs              crates/gaze-term/src/vendor/terminal/title.rs"
    "src/terminal/metadata.rs           crates/gaze-term/src/vendor/terminal/metadata.rs"
    "src/terminal/state.rs              crates/gaze-term/src/vendor/terminal/state.rs"
    "src/agent_resume.rs                crates/gaze-term/src/vendor/agent_resume.rs"
    "src/metadata_tokens.rs             crates/gaze-term/src/vendor/metadata_tokens.rs"
)

# Whole directories copied verbatim (detection manifests are pure data).
DIRS=(
    "src/detect/manifests                crates/gaze-detect/src/vendor/detect/manifests"
)

fetch() {
    if [ ! -d "$cache/.git" ]; then
        echo "cloning herdr into $cache"
        git clone --quiet "$HERDR_REPO" "$cache"
    fi
    git -C "$cache" fetch --quiet origin "$HERDR_COMMIT" 2>/dev/null || git -C "$cache" fetch --quiet
    git -C "$cache" checkout --quiet "$HERDR_COMMIT"
}

# The herdr -> gaze token map (ADR-0005). Order matters, and herdr.dev is
# deliberately preserved: gaze pulls detection manifests from herdr's own
# catalog (ADR-0003).
rename_tokens() {
    sed -e 's|herdr\.dev|@@CATALOG_HOST@@|g' \
        -e 's|"herdr:|"gaze:|g' \
        -e 's|HERDR_|GAZE_|g' \
        -e 's|herdr-agent-state|gaze-agent-state|g' \
        -e 's|herdr-manifest-|gaze-manifest-|g' \
        -e 's|herdr-detect-|gaze-detect-|g' \
        -e 's|herdr_|gaze_|g' \
        -e 's|\bHerdr\b|Gaze|g' \
        -e 's|pane\.report_agent_session|agent.report_session|g' \
        -e 's|pane\.report_agent|agent.report_state|g' \
        -e 's|@@CATALOG_HOST@@|herdr.dev|g'
}

header() {
    local upstream="$1" comment="$2"
    cat <<EOF
${comment} Generated by scripts/revendor.sh from herdr — do not edit by hand.
${comment} Upstream: ${HERDR_REPO}/blob/${HERDR_COMMIT}/${upstream}
${comment} Copyright Ogulcan Celik, licensed under the Apache License 2.0.
${comment} Modified only by the mechanical token map in scripts/revendor.sh.

EOF
}

vendor_file() {
    local upstream="$1" dest="$2" comment="$3"
    mkdir -p "$(dirname "$repo_root/$dest")"
    {
        header "$upstream" "$comment"
        rename_tokens <"$cache/$upstream"
    } >"$repo_root/$dest"
}

apply_patches() {
    [ -d "$patches" ] || return 0
    shopt -s nullglob
    for patch in "$patches"/*.patch; do
        echo "applying $(basename "$patch")"
        git -C "$repo_root" apply "$patch"
    done
    shopt -u nullglob
}

fetch

for entry in "${FILES[@]}"; do
    read -r upstream dest <<<"$entry"
    vendor_file "$upstream" "$dest" "//"
    echo "vendored $dest"
done

for entry in "${DIRS[@]}"; do
    read -r upstream dest <<<"$entry"
    rm -rf "${repo_root:?}/$dest"
    mkdir -p "$repo_root/$dest"
    for file in "$cache/$upstream"/*; do
        name="$(basename "$file")"
        vendor_file "$upstream/$name" "$dest/$name" "#"
    done
    echo "vendored $dest ($(find "$repo_root/$dest" -type f | wc -l) files)"
done

apply_patches

echo
echo "vendored from herdr @ ${HERDR_COMMIT}"
