use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// The state of a wrapped agent, as arbitrated by its wrapper.
///
/// These are herdr's detection states; amon does not add to them.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum AgentState {
    /// Finished, prompt visible, nothing happening.
    Idle,
    /// Actively working.
    Working,
    /// Needs human input.
    Blocked,
    /// Running, but not recognized as an agent.
    Unknown,
}

impl AgentState {
    /// Ordering for `amon status`: the agents that need a human come first.
    pub fn urgency(self) -> u8 {
        match self {
            Self::Blocked => 0,
            Self::Working => 1,
            Self::Idle => 2,
            Self::Unknown => 3,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Idle => "idle",
            Self::Working => "working",
            Self::Blocked => "blocked",
            Self::Unknown => "unknown",
        }
    }
}

/// One connected agent. Lives exactly as long as its wrapper's connection to
/// the daemon; nothing here is persisted.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct AgentEntry {
    /// Generated by the wrapper at launch. Also handed to integration hooks as
    /// `AMON_AGENT_ID`.
    pub id: String,
    /// Agent kind, e.g. `claude`. Free-form so that a wrapper built against a
    /// newer agent list still registers against an older daemon.
    pub agent: String,
    pub state: AgentState,
    /// When the agent last entered [`AgentEntry::state`], unix milliseconds.
    pub state_since: u64,
    pub cwd: String,
    /// Process id of the wrapped agent, not of the wrapper.
    pub pid: u32,
    /// Argv of the wrapped agent, agent name included.
    pub args: Vec<String>,
    pub hostname: String,
    /// Unix milliseconds.
    pub started_at: u64,
    /// Terminal title the agent set, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Reported by integration hooks; absent when none are installed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_session_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_session_path: Option<String>,
}

/// A partial update to an entry. Absent fields are left alone, which is what
/// lets an old wrapper omit fields a newer daemon knows about.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct AgentPatch {
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<AgentState>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state_since: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_session_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_session_path: Option<String>,
}

impl AgentPatch {
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            ..Self::default()
        }
    }

    /// Applies this patch to `entry`, returning whether anything changed.
    pub fn apply(&self, entry: &mut AgentEntry) -> bool {
        let before = entry.clone();
        if let Some(state) = self.state {
            entry.state = state;
        }
        if let Some(state_since) = self.state_since {
            entry.state_since = state_since;
        }
        if self.title.is_some() {
            entry.title = self.title.clone();
        }
        if let Some(agent) = &self.agent {
            entry.agent = agent.clone();
        }
        if self.agent_session_id.is_some() {
            entry.agent_session_id = self.agent_session_id.clone();
        }
        if self.agent_session_path.is_some() {
            entry.agent_session_path = self.agent_session_path.clone();
        }
        *entry != before
    }
}
