use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// The state of a wrapped agent, as arbitrated by its wrapper.
///
/// These are herdr's detection states; amon does not add to them.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum AgentState {
    /// Finished, prompt visible, nothing happening.
    Idle,
    /// Actively working.
    Working,
    /// Needs human input.
    Blocked,
    /// Running, but not recognized as an agent.
    Unknown,
}

impl AgentState {
    /// Ordering for `amon status`: the agents that need a human come first.
    pub fn urgency(self) -> u8 {
        match self {
            Self::Blocked => 0,
            Self::Working => 1,
            Self::Idle => 2,
            Self::Unknown => 3,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Idle => "idle",
            Self::Working => "working",
            Self::Blocked => "blocked",
            Self::Unknown => "unknown",
        }
    }
}

/// One connected agent. Lives exactly as long as its wrapper's connection to
/// the daemon; nothing here is persisted.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct AgentEntry {
    /// Generated by the wrapper at launch. Also handed to integration hooks as
    /// `AMON_AGENT_ID`.
    pub id: String,
    /// Agent kind, e.g. `claude`. Free-form so that a wrapper built against a
    /// newer agent list still registers against an older daemon.
    pub agent: String,
    pub state: AgentState,
    /// When the agent last entered [`AgentEntry::state`], unix milliseconds.
    pub state_since: u64,
    pub cwd: String,
    /// Process id of the wrapped agent, not of the wrapper.
    pub pid: u32,
    /// Argv of the wrapped agent, agent name included.
    pub args: Vec<String>,
    pub hostname: String,
    /// Unix milliseconds.
    pub started_at: u64,
    /// Terminal title the agent set, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Reported by integration hooks; absent when none are installed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_session_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_session_path: Option<String>,
    /// The compositor window hosting the agent's terminal, as an opaque
    /// compositor-native token. Absent off a supported compositor, or when the
    /// wrapper could not identify its window unambiguously — never guessed.
    /// Consumers hand it back to the compositor rather than parsing it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub window: Option<String>,
    /// Display name of the workspace holding [`AgentEntry::window`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workspace: Option<String>,
    /// Whether the agent's terminal *view* has input focus. Absent until a
    /// focus signal arrives; a focused window can host many views, so this is
    /// finer-grained than the compositor's notion of focus.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub focused: Option<bool>,
    /// Whether the terminal view has had focus since the current
    /// [`AgentEntry::state`] began. `Idle` and not seen is "finished but
    /// unnoticed"; consumers combine the two themselves, because this is an
    /// annotation on the state rather than a state of its own.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seen: Option<bool>,
}

/// A partial update to an entry. Absent fields are left alone, which is what
/// lets an old wrapper omit fields a newer daemon knows about.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct AgentPatch {
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<AgentState>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state_since: Option<u64>,
    /// Two levels deep because "clear the title" has to be expressible: absent
    /// means leave alone, `null` means clear, a string means set. An older
    /// daemon reads `null` as absent and merely keeps the stale title.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_or_null"
    )]
    pub title: Option<Option<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_session_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_session_path: Option<String>,
    /// Two levels deep, like [`AgentPatch::title`]: a window that closed has
    /// to be expressible as "no longer known", not merely left stale.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_or_null"
    )]
    pub window: Option<Option<String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_or_null"
    )]
    pub workspace: Option<Option<String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_or_null"
    )]
    pub focused: Option<Option<bool>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_or_null"
    )]
    pub seen: Option<Option<bool>>,
}

/// A field that was present, whether or not it was `null`. `#[serde(default)]`
/// covers the absent case, so together they tell apart absent, `null`, and set.
fn present_or_null<'de, D, T>(deserializer: D) -> Result<Option<Option<T>>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: Deserialize<'de>,
{
    Option::<T>::deserialize(deserializer).map(Some)
}

impl AgentPatch {
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            ..Self::default()
        }
    }

    /// Applies this patch to `entry`, returning whether anything changed.
    pub fn apply(&self, entry: &mut AgentEntry) -> bool {
        let before = entry.clone();
        if let Some(state) = self.state {
            entry.state = state;
        }
        if let Some(state_since) = self.state_since {
            entry.state_since = state_since;
        }
        if let Some(title) = &self.title {
            entry.title = title.clone();
        }
        if let Some(agent) = &self.agent {
            entry.agent = agent.clone();
        }
        if self.agent_session_id.is_some() {
            entry.agent_session_id = self.agent_session_id.clone();
        }
        if self.agent_session_path.is_some() {
            entry.agent_session_path = self.agent_session_path.clone();
        }
        if let Some(window) = &self.window {
            entry.window = window.clone();
        }
        if let Some(workspace) = &self.workspace {
            entry.workspace = workspace.clone();
        }
        if let Some(focused) = self.focused {
            entry.focused = focused;
        }
        if let Some(seen) = self.seen {
            entry.seen = seen;
        }
        *entry != before
    }
}
