use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// The state of a wrapped agent, as arbitrated by its wrapper.
///
/// These are herdr's detection states; amon does not add to them.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum AgentState {
    /// Finished, prompt visible, nothing happening.
    Idle,
    /// Actively working.
    Working,
    /// Needs human input.
    Blocked,
    /// Running, but not recognized as an agent.
    Unknown,
}

impl AgentState {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Idle => "idle",
            Self::Working => "working",
            Self::Blocked => "blocked",
            Self::Unknown => "unknown",
        }
    }
}

/// One connected agent. Lives exactly as long as its wrapper's connection to
/// the daemon; nothing here is persisted.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct AgentEntry {
    /// Generated by the wrapper at launch. Also handed to integration hooks as
    /// `AMON_AGENT_ID`.
    pub id: String,
    /// Agent kind, e.g. `claude`. Free-form so that a wrapper built against a
    /// newer agent list still registers against an older daemon.
    pub agent: String,
    pub state: AgentState,
    /// When the agent last entered [`AgentEntry::state`], unix milliseconds.
    pub state_since: u64,
    pub cwd: String,
    /// Process id of the wrapped agent, not of the wrapper.
    pub pid: u32,
    /// Argv of the wrapped agent, agent name included.
    pub args: Vec<String>,
    pub hostname: String,
    /// Unix milliseconds.
    pub started_at: u64,
    /// Terminal title the agent set, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Reported by integration hooks; absent when none are installed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_session_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_session_path: Option<String>,
    /// The compositor window hosting the agent's terminal, as an opaque
    /// compositor-native token. Absent off a supported compositor, or when the
    /// wrapper could not identify its window unambiguously — never guessed.
    /// Consumers hand it back to the compositor rather than parsing it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub window: Option<String>,
    /// Display name of the workspace holding [`AgentEntry::window`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workspace: Option<String>,
    /// The Project [`AgentEntry::cwd`] belongs to: the repository it is in,
    /// named by its root directory. A linked worktree's Project is the
    /// repository it was cut from, not the worktree's own directory — a
    /// worktree's path names neither its project nor its branch.
    ///
    /// Absent outside a repository, where the directory itself identifies the
    /// agent and a consumer shows that instead.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// Where inside its checkout the agent sits, relative to the checkout
    /// root. Absent at the root, which is the ordinary case, and absent
    /// wherever [`AgentEntry::project`] is. Relative to the *worktree* for an
    /// agent in one, because the repository does not contain that path.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subpath: Option<String>,
    /// The git branch [`AgentEntry::cwd`] is on, when it is on one.
    ///
    /// Absent outside a repository, and absent on a detached HEAD — which has
    /// a commit but no branch. Read from `.git/HEAD` rather than by running
    /// git, so a directory git would understand and this does not reads as
    /// absent too: a blank column rather than a wrong one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    /// Whether the agent's terminal *view* has input focus. Absent until a
    /// focus signal arrives; a focused window can host many views, so this is
    /// finer-grained than the compositor's notion of focus.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub focused: Option<bool>,
    /// Whether the terminal view has had focus since the current
    /// [`AgentEntry::state`] began. `Idle` and not seen is "finished but
    /// unnoticed" — an annotation on the state rather than a state of its own,
    /// which is why [`AgentEntry::attention`] exists: to combine the two in one
    /// place instead of leaving every consumer to invent the same rule.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seen: Option<bool>,
    /// Set when this agent runs inside a herdr session rather than under an
    /// amon wrapper.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub herdr: Option<HerdrInfo>,
}

/// Where a herdr-hosted agent lives inside herdr. Present exactly on entries
/// the daemon's herdr module projects; wrapped agents never carry it. The
/// socket travels with the entry so a consumer that wants to act on the agent
/// (the focus hop) does not re-derive herdr's path rules.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct HerdrInfo {
    /// Absolute path of the session's JSON API socket.
    pub socket: String,
    /// Session name; absent for herdr's default session.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session: Option<String>,
    /// The pane currently hosting the agent (`w1:p1`) — what `agent.focus`
    /// takes. Pane ids change when panes move across herdr workspaces, so the
    /// daemon refreshes this and consumers must not cache it.
    pub pane: String,
}

impl AgentEntry {
    /// Ordering by what wants a human, most first — the one ranking amon
    /// sorts, draws and jumps by.
    ///
    /// Over the entry rather than the state, because the rank's second place is
    /// not a state at all: "done" is [`AgentState::Idle`] carrying
    /// [`AgentEntry::seen`] false, finished and unnoticed. That it outranks a
    /// working agent is the point. Work in progress asks nothing of anyone;
    /// work that has finished and not been looked at is the likeliest thing in
    /// the list to be waiting on you.
    ///
    /// [`AgentState::Unknown`] sorts last: an unrecognised process is usually
    /// not an agent, and ranking it above anything would cry wolf.
    pub fn attention(&self) -> u8 {
        match self.state {
            AgentState::Blocked => 0,
            AgentState::Idle if self.seen == Some(false) => 1,
            AgentState::Working => 2,
            AgentState::Idle => 3,
            AgentState::Unknown => 4,
        }
    }

    /// Whether this agent is worth taking someone to.
    ///
    /// An agent at rest is not. It asks for nothing, so moving the focus onto
    /// it would be amon interrupting on its own account — which is why
    /// `amon focus` leaves a workspace of idle agents exactly as the
    /// compositor left it.
    pub fn wants_attention(&self) -> bool {
        match self.state {
            AgentState::Blocked | AgentState::Working => true,
            AgentState::Idle => self.seen == Some(false),
            AgentState::Unknown => false,
        }
    }
}

/// A partial update to an entry. Absent fields are left alone, which is what
/// lets an old wrapper omit fields a newer daemon knows about.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct AgentPatch {
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<AgentState>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state_since: Option<u64>,
    /// Two levels deep because "clear the title" has to be expressible: absent
    /// means leave alone, `null` means clear, a string means set. An older
    /// daemon reads `null` as absent and merely keeps the stale title.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_or_null"
    )]
    pub title: Option<Option<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_session_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_session_path: Option<String>,
    /// Two levels deep, like [`AgentPatch::title`]: a window that closed has
    /// to be expressible as "no longer known", not merely left stale.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_or_null"
    )]
    pub window: Option<Option<String>>,
    /// Where the agent is working now. An agent can change directory — into a
    /// worktree, into a sibling checkout — and takes its Project and its
    /// branch with it, so all four move together or none of them do.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    /// Two levels deep, like the branch below: an agent that walks out of a
    /// repository has to be able to say so rather than keep naming the last
    /// one it was in.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_or_null"
    )]
    pub project: Option<Option<String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_or_null"
    )]
    pub subpath: Option<Option<String>>,
    /// Two levels deep, like [`AgentPatch::window`]: checking out a detached
    /// HEAD has to be expressible as "no longer on a branch" rather than
    /// leaving the old name standing.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_or_null"
    )]
    pub branch: Option<Option<String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_or_null"
    )]
    pub workspace: Option<Option<String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_or_null"
    )]
    pub focused: Option<Option<bool>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_or_null"
    )]
    pub seen: Option<Option<bool>>,
}

/// A field that was present, whether or not it was `null`. `#[serde(default)]`
/// covers the absent case, so together they tell apart absent, `null`, and set.
fn present_or_null<'de, D, T>(deserializer: D) -> Result<Option<Option<T>>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: Deserialize<'de>,
{
    Option::<T>::deserialize(deserializer).map(Some)
}

impl AgentPatch {
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            ..Self::default()
        }
    }

    /// Applies this patch to `entry`, returning whether anything changed.
    pub fn apply(&self, entry: &mut AgentEntry) -> bool {
        let before = entry.clone();
        if let Some(state) = self.state {
            entry.state = state;
        }
        if let Some(state_since) = self.state_since {
            entry.state_since = state_since;
        }
        if let Some(title) = &self.title {
            entry.title = title.clone();
        }
        if let Some(agent) = &self.agent {
            entry.agent = agent.clone();
        }
        if self.agent_session_id.is_some() {
            entry.agent_session_id = self.agent_session_id.clone();
        }
        if self.agent_session_path.is_some() {
            entry.agent_session_path = self.agent_session_path.clone();
        }
        if let Some(window) = &self.window {
            entry.window = window.clone();
        }
        if let Some(workspace) = &self.workspace {
            entry.workspace = workspace.clone();
        }
        if let Some(cwd) = &self.cwd {
            entry.cwd = cwd.clone();
        }
        if let Some(project) = &self.project {
            entry.project = project.clone();
        }
        if let Some(subpath) = &self.subpath {
            entry.subpath = subpath.clone();
        }
        if let Some(branch) = &self.branch {
            entry.branch = branch.clone();
        }
        if let Some(focused) = self.focused {
            entry.focused = focused;
        }
        if let Some(seen) = self.seen {
            entry.seen = seen;
        }
        *entry != before
    }
}
